### ISSUE TITLE
InvalidCastException when update with where in

### ISSUE THREAD

**Issue by 11038215** [Coldairarrow/EFCore.Sharding#64] opened 2020-11-05 11:30 UTC
**Description**
An InvalidCastExpression is thrown when using UpdateSql with WHERE IN. For example:

var list = _repository.GetIQueryable<>(Poster).Where(x => postIds.Contains(x.Id)).ToListAsync();
// No problem

_repository.UpdateSql<Poster>(x => postIds.Contains(x.Id),(("Name",UpdateType.Equal,"小明"));

**Exception**
If you are seeing an exception, include the full exceptions details (message and stack trace).
Unable to cast object of type 'Microsoft.EntityFrameworkCore.Query.SqlExpressions.SqlParameterExpression' to type 'Microsoft.EntityFrameworkCore.Query.SqlExpressions.SqlConstantExpression'.
at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.VisitIn(InExpression inExpression)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Pomelo.EntityFrameworkCore.MySql.Query.ExpressionVisitors.Internal.MySqlQuerySqlGenerator.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.VisitSqlBinary(SqlBinaryExpression sqlBinaryExpression)
   at Pomelo.EntityFrameworkCore.MySql.Query.ExpressionVisitors.Internal.MySqlQuerySqlGenerator.VisitSqlBinary(SqlBinaryExpression sqlBinaryExpression)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Pomelo.EntityFrameworkCore.MySql.Query.ExpressionVisitors.Internal.MySqlQuerySqlGenerator.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.VisitSelect(SelectExpression selectExpression)
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.GetCommand(SelectExpression selectExpression)
   at EFCore.Sharding.Extention.ToSql(IQueryable query) in 

Database Provider: MySql

**Comment by Coldairarrow** [comment] 2020-11-05 12:46
UpdateSql And DeleteSql Can Not Use Contains

**Comment by Coldairarrow** [comment] 2020-11-05 12:47
just support simple like = > < &&

**Comment by Coldairarrow** [comment] 2020-11-23 08:59
Duplicate of #67

**Comment by Coldairarrow** [comment] 2020-11-28 04:44
5.0已支持

**Closed by Coldairarrow** 2020-11-28 04:44 UTC
Labels: enhancement
